// Generated by CoffeeScript 1.9.2
(function() {
  this.Invitations.after.insert(function(userId, doc) {
    return Email.send({
      from: "noreply@serviceme.com",
      to: doc.email,
      subject: "Invitation to serviceme.com",
      text: "Hi\n\nYou have received an invitation to serviceme\njust visit: " + (Meteor.absoluteUrl()) + "invitation/" + doc._id + "\n\nThanks"
    });
  });

}).call(this);

//# sourceMappingURL=hooks.js.map
