that = this
@Schemas ||= {}
@Schemas.UserCountry = new SimpleSchema(
  name: type: String
  code:
    type: String
    regEx: /^[A-Z]{2}$/)
@Schemas.UserProfile = new SimpleSchema(
  firstName:
    type: String
    regEx: /^[a-zA-Z-]{2,25}$/
    optional: true
  lastName:
    type: String
    regEx: /^[a-zA-Z]{2,25}$/
    optional: true
  birthday:
    type: Date
    optional: false
  gender:
    type: String
    allowedValues: [
      'Male'
      'Female'
    ]
    optional: true
  organization:
    type: String
    regEx: /^[a-z0-9A-z .]{3,30}$/
    optional: true
  website:
    type: String
    regEx: SimpleSchema.RegEx.Url
    optional: true
  bio:
    type: String
    optional: true
  country:
    type: @Schemas.UserCountry
    optional: true
)

# ---
# generated by js2coffee 2.0.4