// Generated by CoffeeScript 1.9.2
(function() {
  this.Bugs.attachSchema(this.Schemas.Bug);

  this.Bugs._transform = function(bug) {
    return _.extend(bug, this.Transforms.Bug);
  };

}).call(this);

//# sourceMappingURL=main.js.map
