// Generated by CoffeeScript 1.3.3
(function() {

  Template.bugs.helpers({
    sortedBugs: function() {
      return _.sortBy(this.bugs.fetch(), function(b) {
        return -b.createdAt;
      });
    }
  });

}).call(this);
