// Generated by CoffeeScript 1.9.2
(function() {
  this.UserTags.attachSchema(this.Schemas.UserTag);

  this.UserTags._transform = function(UserTag) {
    return _.extend(UserTag, this.Transforms.UserTag);
  };

}).call(this);

//# sourceMappingURL=main.js.map
